import { Inter } from "next/font/google";

import "./globals.scss";
import NavBarCustom from "@/components/NavBarCustom";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBarCustom />
        {children}
        <footer className="">
          <div className="container-fluid">
            <span className="navbar-brand mb-0 h1 text-light">
              HUSE | Weather
            </span>
          </div>
        </footer>
      </body>
    </html>
  );
}
