/*********************************************************************************
 * WEB422 – Assignment 2
 * I declare that this assignment is my own work in accordance with Seneca Academic Policy.
 * No part of this assignment has been copied manually or electronically from any other source
 * (including web sites) or distributed to other students.
 *
 * Name: Ali Huseynli Student ID: 124694233 Date: 07/05/2024
 *
 *
 ********************************************************************************/

import { Inter } from "next/font/google";

import "./globals.scss";
import NavBarCustom from "@/components/NavBarCustom";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBarCustom />
        {children}
      </body>
    </html>
  );
}
